use_frameworks!
platform :ios, '9.3'

target 'ElderCare_UserModule_Example' do
  pod 'ElderCare_UserModule', :path => '../'

  target 'ElderCare_UserModule_Tests' do
    inherit! :search_paths

  end
end
