use_frameworks!
platform :ios, '10.0'

target 'ElderCare_UserModule_Example' do
  pod 'ElderCare_UserModule', :path => '../'

  target 'ElderCare_UserModule_Tests' do
    inherit! :search_paths

  end
end
